---
- name: Install Elasticsearch
  hosts: elasticsearch
  handlers:
    - name: restart Elasticsearch
      become: true
      service:
        name: elasticsearch
        state: restarted
  tasks:
    - name: "Download Elasticsearch's rpm"
      get_url:
        url: "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ elk_stack_version }}-x86_64.rpm"
        dest: "/tmp/elasticsearch-{{ elk_stack_version }}-x86_64.rpm"
      register: download_elastic
      until: download_elastic is succeeded
    - name: Install Elasticsearch
      become: true
      yum:
        name: "/tmp/elasticsearch-{{ elk_stack_version }}-x86_64.rpm"
        state: present
    - name: Start elasticsearch
      become: true
      systemd:
        name: elasticsearch
        state: started
        enabled: true
    - name: Configure Elasticsearch
      become: true
      template:
        src: elasticsearch.yml.j2
        dest: /etc/elasticsearch/elasticsearch.yml
      notify: restart Elasticsearch
      tags: elasticsearch 
- name: install kibana
  hosts: kibana
  handlers:
    - name: restart Kibana
      become: true
      service:
        name: kibana
        state: restarted
        enabled: true
  tasks:
    - name: "Download Kibana's rpm" 
      get_url:      
        url: "https://artifacts.elastic.co/downloads/kibana/kibana-{{ kibana_stack_version }}-x86_64.rpm"
        dest: "/tmp/kibana-{{ kibana_stack_version }}-x86_64.rpm"
      register: download_kibana        
      until: download_kibana is succeeded
    - name: Install Kibana
      become: true
      yum:
         name: "/tmp/kibana-{{ kibana_stack_version }}-x86_64.rpm"
         state: present
    - name: Start kibana
      become: true
      systemd:
        name: kibana
        state: started
        enabled: true
    - name: Configure Kibana
      become: true
      template:
        src:  kibana.yml.j2
        dest: /etc/kibana/kibana.yml
      notify: restart Kibana
      tags: kibana
- name: install filebeat
  hosts: elasticsearch
  handlers:
    - name: restart filebeat
      become: true
      service:
        name: filebeat
        state: restarted
        enabled: true
  tasks:
    - name: "Download filebeat rpm"
      get_url:
        url: "https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-{{ elk_stack_version }}-x86_64.rpm"
        dest: "/tmp/filebeat-{{ elk_stack_version }}-x86_64.rpm"
      register: download_filebeat
      until: download_filebeat is succeeded
    - name: Install filebeat
      become: true
      yum:
         name: "/tmp/filebeat-{{ elk_stack_version }}-x86_64.rpm"
         state: present
    - name: Start filebeat
      become: true
      systemd:
        name: filebeat
        state: started
        enabled: true
    - name: Configure filebeat
      become: true
      template:
        src:  filebeat.yml.j2
        dest: /etc/filebeat/filebeat.yml
      notify: restart filebeat
    - name: Set filebeat systemwork
      become: true
      command:
        cmd: filebeat modules enable system
        chdir: /usr/share/filebeat/bin
    - name: Load Kibana dashboard
      become: true
      command:
        cmd: filebeat setup
        chdir: /usr/share/filebeat/bin
      register: filebeat_setup
      until: filebeat_setup is succeded
      notify: restart filebeat
      tags: filebeat

